"""create initial database schema

Revision ID: 2469cac7017b
Revises: 
Create Date: 2026-09-30 13:59:06.248103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2469cac7017b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMINISTRATOR', 'ADMINISTRATOR', 'MODERATOR', 'SUPPORT', name='administrator_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PENDING', name='administrator_status'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administrators_email'), 'administrators', ['email'], unique=True)
    op.create_table('models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('model_type', sa.Enum('PRODUCTION', 'EXPERIMENTAL', 'DEVELOPMENT', name='model_type'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'READY', 'ARCHIVED', name='model_status'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('observed_accuracy', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('board_size', sa.Integer(), nullable=False),
    sa.Column('maximum_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_version'), 'models', ['version'], unique=True)
    op.create_table('settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_number', sa.String(length=50), nullable=False),
    sa.Column('game', sa.String(length=100), nullable=False),
    sa.Column('board_size', sa.Integer(), nullable=False),
    sa.Column('mine_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('recommended_positions', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ANALYZED', 'CONFIRMED', 'PUBLISHED', 'RESULT_PENDING', 'SUCCESS', 'FAILED', name='signal_status'), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_signal_number'), 'signals', ['signal_number'], unique=True)
    op.create_index(op.f('ix_signals_status'), 'signals', ['status'], unique=False)
    op.create_table('telegram_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.String(length=100), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_channels_channel_id'), 'telegram_channels', ['channel_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('administrator_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'PUBLISH', 'CONFIRM', 'SYNC', 'RESULT', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['administrator_id'], ['administrators.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_administrator_id'), 'audit_logs', ['administrator_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('safe_positions', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('predicted_mine_positions', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_model_id'), 'predictions', ['model_id'], unique=False)
    op.create_index(op.f('ix_predictions_signal_id'), 'predictions', ['signal_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('actual_mine_positions', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('actual_safe_positions', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('correct_predictions', sa.Integer(), nullable=False),
    sa.Column('incorrect_predictions', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='result_status'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_signal_id'), 'results', ['signal_id'], unique=True)
    op.create_table('telegram_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHED', 'SYNCED', 'PARSED', 'FAILED', name='telegram_message_status'), nullable=False),
    sa.Column('sync_status', sa.Enum('PENDING', 'SYNCED', 'FAILED', name='telegram_sync_status'), nullable=False),
    sa.Column('parse_status', sa.Enum('PENDING', 'SUCCESS', 'PARTIAL', 'FAILED', name='telegram_parse_status'), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('forwards', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['telegram_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_messages_channel_id'), 'telegram_messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_telegram_messages_signal_id'), 'telegram_messages', ['signal_id'], unique=False)
    op.create_index(op.f('ix_telegram_messages_telegram_message_id'), 'telegram_messages', ['telegram_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_messages_telegram_message_id'), table_name='telegram_messages')
    op.drop_index(op.f('ix_telegram_messages_signal_id'), table_name='telegram_messages')
    op.drop_index(op.f('ix_telegram_messages_channel_id'), table_name='telegram_messages')
    op.drop_table('telegram_messages')
    op.drop_index(op.f('ix_results_signal_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_predictions_signal_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_model_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_audit_logs_administrator_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_telegram_channels_channel_id'), table_name='telegram_channels')
    op.drop_table('telegram_channels')
    op.drop_index(op.f('ix_signals_status'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_number'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_models_version'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_administrators_email'), table_name='administrators')
    op.drop_table('administrators')
    # ### end Alembic commands ###