"""add model relationship to signals

Revision ID: 348fc00cc407
Revises: 2469cac7017b
Create Date: 2026-10-01 02:32:58.971199

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348fc00cc407'
down_revision: Union[str, Sequence[str], None] = '2469cac7017b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('model_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_signals_model_id'), 'signals', ['model_id'], unique=False)
    op.create_foreign_key(None, 'signals', 'models', ['model_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'signals', type_='foreignkey')
    op.drop_index(op.f('ix_signals_model_id'), table_name='signals')
    op.drop_column('signals', 'model_id')
    # ### end Alembic commands ###